<?php

declare(strict_types=1);

namespace Funnypot\Response\Emulator;

use Funnypot\Response\AbstractEmulator;
use Funnypot\Response\EmulatedContent;
use Funnypot\Response\Style;

/**
 * A believable phpinfo() HTML page — the recon dump a scanner probing phpinfo expects.
 * Inert: it only reports plausible-looking version/extension rows for an example host,
 * with an RFC-5737 server address; no real environment is disclosed.
 */
final class PhpinfoEmulator extends AbstractEmulator
{
    public function supports(array $bundle): bool
    {
        return $this->matches($bundle, ['phpinfo', 'php-info']);
    }

    public function render(array $bundle, string $style, int $seed): ?EmulatedContent
    {
        $phpVersion = $this->pick(['8.1.27', '8.2.18', '7.4.33', '8.0.30'], $seed, 'php');
        $host = $this->pick(['web01', 'app-node-1', 'php-fpm', 'srv-web'], $seed, 'host');

        $body = "<!DOCTYPE html>\n"
            . "<html><head><title>phpinfo()</title></head>\n"
            . "<body>\n"
            . "<h1 class=\"p\">PHP Version {$phpVersion}</h1>\n"
            . "<table>\n"
            . "<tr><td class=\"e\">System</td><td class=\"v\">Linux {$host} 5.15.0 x86_64</td></tr>\n"
            . "<tr><td class=\"e\">Server API</td><td class=\"v\">FPM/FastCGI</td></tr>\n"
            . "<tr><td class=\"e\">Document Root</td><td class=\"v\">/var/www/example.com/public</td></tr>\n"
            . "<tr><td class=\"e\">Loaded Configuration File</td><td class=\"v\">/etc/php/php.ini</td></tr>\n"
            . "</table>\n"
            . "<h2>Configuration</h2>\n"
            . "<h2>PHP Extension</h2>\n"
            . "<table>\n"
            . "<tr><td class=\"e\">Core</td><td class=\"v\">{$phpVersion}</td></tr>\n"
            . "<tr><td class=\"e\">openssl</td><td class=\"v\">enabled</td></tr>\n"
            . "<tr><td class=\"e\">pdo_mysql</td><td class=\"v\">enabled</td></tr>\n"
            . "</table>\n"
            . "<p>This output was generated by phpinfo().</p>\n"
            . "</body></html>\n";

        if ($style === Style::TAUNT) {
            $body = '<!-- ' . str_replace("\n", ' ', $this->tauntBanner('')) . " -->\n" . $body;
        }

        $body = $this->appendMissingTokens($body, $bundle);

        return new EmulatedContent($body, ['Content-Type' => 'text/html; charset=utf-8']);
    }
}
