<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-emulators` — DO NOT EDIT.

return array (
  0 => 
  array (
    'id' => 'attack-confluence-26134',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'confluence',
      3 => 'ognl',
      4 => 'cve-2022-26134',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '\\$\\{.*(?:#context|#cmd|@java|@org\\.|getRuntime|ProcessBuilder|Runtime)',
        'dotall' => true,
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html;charset=UTF-8',
        'X-Cmd-Response' => '{{canned.uid}}',
      ),
      'body' => '<!DOCTYPE html><html><head><title>Log In - Confluence</title></head><body><div id="main">Confluence</div></body></html>',
    ),
  ),
  1 => 
  array (
    'id' => 'attack-phpcgi-1823',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'php-cgi',
      2 => 'source-disclosure',
      3 => 'cve-2012-1823',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'query',
        'regex' => '^-[sdw](?:[+ &=]|$)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html',
      ),
      'body' => '<code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span>
<span style="color: #007700">$db </span><span style="color: #0000BB">= new mysqli</span><span style="color: #007700">(</span><span style="color: #DD0000">"localhost"</span><span style="color: #007700">, </span><span style="color: #DD0000">"root"</span><span style="color: #007700">, </span><span style="color: #DD0000">"S3cr3tP@ss"</span><span style="color: #007700">);<br /></span>
<span style="color: #0000BB">?&gt;</span>
</span></code>
',
    ),
  ),
  2 => 
  array (
    'id' => 'attack-shellshock',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'shellshock',
      3 => 'cve-2014-6271',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'header',
        'contains' => '() {',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.passwd}}',
    ),
  ),
  3 => 
  array (
    'id' => 'attack-struts-ognl',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'struts',
      3 => 'ognl',
      4 => 'cve-2017-5638',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'header:Content-Type',
        'regex' => '%\\{.*(?:#context|#cmd|#_memberAccess|\\(#|multipart/form-data.*[({])',
        'dotall' => true,
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '{{canned.uid}}',
    ),
  ),
  4 => 
  array (
    'id' => 'attack-phpunit-rce',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'phpunit',
      3 => 'cve-2017-9841',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'path',
        'contains' => 'eval-stdin.php',
      ),
      1 => 
      array (
        'in' => 'body',
        'regex' => 'md5\\(["\']?([^)"\']+)["\']?\\)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '{{compute.md5:match.1}}',
    ),
  ),
  5 => 
  array (
    'id' => 'attack-xxe',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'xxe',
      2 => 'file-disclosure',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'body',
        'regex' => '<!ENTITY\\s+\\S+\\s+SYSTEM\\s+["\'\\s]*(?:file:|https?:|php:)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'application/xml; charset=utf-8',
      ),
      'body' => '{{canned.passwd}}',
    ),
  ),
  6 => 
  array (
    'id' => 'attack-lfi-smbconf',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
      3 => 'smb',
      4 => 'citrix',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => 'smb\\.conf',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '[global]
   workgroup = WORKGROUP
   server string = %h server (Samba)
   security = user
   map to guest = Bad User
   log file = /var/log/samba/log.%m
   max log size = 1000
[printers]
   comment = All Printers
   path = /var/spool/samba
   browseable = no
',
    ),
  ),
  7 => 
  array (
    'id' => 'attack-lfi-environ',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
      3 => 'proc',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '/proc/self/environ',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.environ}}',
    ),
  ),
  8 => 
  array (
    'id' => 'attack-lfi-shadow',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => 'etc/shadow',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.shadow}}',
    ),
  ),
  9 => 
  array (
    'id' => 'attack-lfi-group',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => 'etc/group',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.group}}',
    ),
  ),
  10 => 
  array (
    'id' => 'attack-lfi-windows',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
      3 => 'windows',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:win\\.ini|boot\\.ini|windows[\\\\/]|system32|c:[\\\\/])',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.winini}}',
    ),
  ),
  11 => 
  array (
    'id' => 'attack-lfi-unix',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:\\.\\.[\\\\/]|%2e%2e|\\.\\.%2f|\\.\\.%5c|etc/passwd|etc/shadow|/proc/self/environ|wp-config\\.php%00)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.passwd}}',
    ),
  ),
  12 => 
  array (
    'id' => 'attack-cmdi-windows',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'command-injection',
      3 => 'windows',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:[;|&\\n`]|\\$\\(|%0a|%7c|%26)\\s*(?:ipconfig|systeminfo|dir\\b|type\\s)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => 'Windows IP Configuration

Ethernet adapter Ethernet0:
   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : 192.0.2.15
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.0.2.1
',
    ),
  ),
  13 => 
  array (
    'id' => 'attack-cmdi-unix',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'command-injection',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:[;|&\\n`]|\\$\\(|%0a|%7c|%26)\\s*(?:id|whoami|uname|cat\\s|ls\\s|pwd|ifconfig)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.uid}}',
    ),
  ),
  14 => 
  array (
    'id' => 'attack-ssti-twig',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'ssti',
      2 => 'twig',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:\\{\\{|\\$\\{|\\#\\{|<%=?)\\s*7\\s*\\*\\s*[\'"]7',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '7777777
',
    ),
  ),
  15 => 
  array (
    'id' => 'attack-ssti-numeric',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'ssti',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:\\{\\{|\\$\\{|\\#\\{|<%=?)\\s*7\\s*\\*\\s*7',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '49
',
    ),
  ),
  16 => 
  array (
    'id' => 'attack-php-glastopf',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'php-injection',
      3 => 'glastopf',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '\\[php\\][\\s\\S]*?(?:system|passthru|exec|shell_exec|popen)\\s*\\(\\s*[\'"]?(?:id|whoami|uname)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '{{canned.uid}}',
    ),
  ),
  17 => 
  array (
    'id' => 'attack-sqli',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'sqli',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:\'\\s*or\\s*\'?1\'?\\s*=\\s*\'?1|"\\s*or\\s*"?1"?\\s*=|\\bunion\\s+(?:all\\s+)?select\\b|\\bor\\s+1\\s*=\\s*1\\b|information_schema|sleep\\(\\d|\'\\s*--|\\bwaitfor\\s+delay\\b)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 1
',
    ),
  ),
  18 => 
  array (
    'id' => 'attack-open-redirect',
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'redirect',
      2 => 'open-redirect',
    ),
    'status' => 302,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'query',
        'regex' => '(?:url|redirect|redirect_uri|redirect_url|next|dest|destination|return|returnurl|returnto|goto|target|continue|forward)=((?:https?:)?//[^&]+)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
        'Location' => '{{urldecode:match.1}}',
      ),
      'body' => '<html><head><title>302 Found</title></head><body>Redirecting...</body></html>',
    ),
  ),
  19 => 
  array (
    'id' => 'attack-xss',
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'xss',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '<script[^>]*>.*?</script>|<svg[^>]*>.*?</svg>|<img[^>]*\\son\\w+\\s*=[^>]*>|<[a-z][a-z0-9]*[^>]*\\son(?:error|load|mouseover|focus)\\s*=[^>]*>',
        'dotall' => true,
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '<!doctype html><html><head><title>Search</title></head><body>
<h1>Search results</h1><p>No results found for: {{match.0}}</p>
</body></html>
',
    ),
  ),
);
