<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-protocols` — DO NOT EDIT.

return array (
  'ftp' => 
  array (
    'listen' => 
    array (
      0 => 21,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'ftp',
    ),
    'banner' => '220 (vsFTPd 3.0.5)
',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'prefix' => 'USER',
        ),
        'send' => '331 Please specify the password.
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'PASS',
        ),
        'send' => '230 Login successful.
',
      ),
      2 => 
      array (
        'match' => 
        array (
          'prefix' => 'SYST',
        ),
        'send' => '215 UNIX Type: L8
',
      ),
      3 => 
      array (
        'match' => 
        array (
          'prefix' => 'FEAT',
        ),
        'send' => '211-Features:
 PASV
 UTF8
211 End
',
      ),
      4 => 
      array (
        'match' => 
        array (
          'prefix' => 'PWD',
        ),
        'send' => '257 "/" is the current directory
',
      ),
      5 => 
      array (
        'match' => 
        array (
          'prefix' => 'TYPE',
        ),
        'send' => '200 Switching to Binary mode.
',
      ),
      6 => 
      array (
        'match' => 
        array (
          'regex' => '^(LIST|NLST|MLSD)\\b',
        ),
        'send' => '150 Here comes the directory listing.
226 Directory send OK.
',
      ),
      7 => 
      array (
        'match' => 
        array (
          'prefix' => 'QUIT',
        ),
        'send' => '221 Goodbye.
',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '500 Unknown command.
',
    ),
  ),
  'memcached' => 
  array (
    'listen' => 
    array (
      0 => 11211,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'memcached',
      2 => 'cache',
    ),
    'banner' => '',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'equals' => 'version',
        ),
        'send' => 'VERSION 1.6.21
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'stats',
        ),
        'send' => 'STAT pid 1
STAT version 1.6.21
STAT uptime 824113
STAT curr_connections 1
STAT curr_items 0
END
',
      ),
      2 => 
      array (
        'match' => 
        array (
          'prefix' => 'get',
        ),
        'send' => 'END
',
      ),
      3 => 
      array (
        'match' => 
        array (
          'regex' => '^(set|add|replace)\\b',
        ),
        'send' => 'STORED
',
      ),
      4 => 
      array (
        'match' => 
        array (
          'prefix' => 'quit',
        ),
        'send' => '',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => 'ERROR
',
    ),
  ),
  'redis' => 
  array (
    'listen' => 
    array (
      0 => 6379,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'redis',
      2 => 'cache',
    ),
    'banner' => '',
    'framing' => 'resp',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'equals' => 'PING',
        ),
        'send' => '+PONG
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'AUTH',
        ),
        'send' => '+OK
',
      ),
      2 => 
      array (
        'match' => 
        array (
          'prefix' => 'INFO',
        ),
        'send' => 
        array (
          'bulk' => '# Server
redis_version:7.2.4
redis_mode:standalone
os:Linux 5.15.0 x86_64
arch_bits:64
process_id:1
run_id:{{fake.redis_runid:hex:40}}
tcp_port:6379
uptime_in_seconds:824113
# Clients
connected_clients:1
# Memory
used_memory_human:1.02M
maxmemory_human:0B
# Keyspace
db0:keys=3,expires=0,avg_ttl=0',
        ),
      ),
      3 => 
      array (
        'match' => 
        array (
          'prefix' => 'CONFIG GET',
        ),
        'send' => 
        array (
          'bulk_array' => 
          array (
            0 => 'dir',
            1 => '/var/lib/redis',
          ),
        ),
      ),
      4 => 
      array (
        'match' => 
        array (
          'prefix' => 'COMMAND',
        ),
        'send' => '*0
',
      ),
      5 => 
      array (
        'match' => 
        array (
          'prefix' => 'SELECT',
        ),
        'send' => '+OK
',
      ),
      6 => 
      array (
        'match' => 
        array (
          'prefix' => 'CLIENT',
        ),
        'send' => '+OK
',
      ),
      7 => 
      array (
        'match' => 
        array (
          'regex' => '^(GET|SET|DEL|KEYS|SCAN|HGETALL|LRANGE|TYPE|TTL|EXISTS)\\b',
        ),
        'send' => '$-1
',
      ),
      8 => 
      array (
        'match' => 
        array (
          'prefix' => 'QUIT',
        ),
        'send' => '+OK
',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '-ERR unknown command
',
    ),
  ),
  'smtp' => 
  array (
    'listen' => 
    array (
      0 => 25,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'smtp',
      2 => 'mail',
    ),
    'banner' => '220 mail.example.com ESMTP Postfix (Ubuntu)
',
    'framing' => 'line',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'prefix' => 'EHLO',
        ),
        'send' => '250-mail.example.com
250-PIPELINING
250-SIZE 10240000
250 8BITMIME
',
      ),
      1 => 
      array (
        'match' => 
        array (
          'prefix' => 'HELO',
        ),
        'send' => '250 mail.example.com
',
      ),
      2 => 
      array (
        'match' => 
        array (
          'prefix' => 'MAIL',
        ),
        'send' => '250 2.1.0 Ok
',
      ),
      3 => 
      array (
        'match' => 
        array (
          'prefix' => 'RCPT',
        ),
        'send' => '250 2.1.5 Ok
',
      ),
      4 => 
      array (
        'match' => 
        array (
          'prefix' => 'DATA',
        ),
        'send' => '354 End data with <CR><LF>.<CR><LF>
',
      ),
      5 => 
      array (
        'match' => 
        array (
          'prefix' => 'RSET',
        ),
        'send' => '250 2.0.0 Ok
',
      ),
      6 => 
      array (
        'match' => 
        array (
          'prefix' => 'NOOP',
        ),
        'send' => '250 2.0.0 Ok
',
      ),
      7 => 
      array (
        'match' => 
        array (
          'prefix' => 'QUIT',
        ),
        'send' => '221 2.0.0 Bye
',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '502 5.5.2 Error: command not recognized
',
    ),
  ),
  'ssh' => 
  array (
    'listen' => 
    array (
      0 => 2222,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'ssh',
      2 => 'banner',
    ),
    'banner' => 'SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.6
',
    'framing' => 'raw',
    'rules' => 
    array (
      0 => 
      array (
        'match' => 
        array (
          'regex' => '^SSH-',
        ),
        'send' => '',
        'close' => true,
      ),
    ),
    'default' => 
    array (
      'send' => '',
    ),
  ),
  'telnet' => 
  array (
    'listen' => 
    array (
      0 => 23,
    ),
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'protocol',
      1 => 'telnet',
    ),
    'banner' => '
Ubuntu 22.04.3 LTS
login: ',
    'framing' => 'line',
    'rules' => 
    array (
    ),
    'default' => 
    array (
      'send' => 'Password: 
Login incorrect

login: ',
    ),
  ),
);
