<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-catalog` — DO NOT EDIT.

return array (
  'attack-citrix-bleed-4966' => 
  array (
    'id' => 'attack-citrix-bleed-4966',
    'kind' => 'attack',
    'title' => 'Citrix Bleed 4966',
    'category' => 'other',
    'cve' => 'CVE-2023-4966',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/84-citrix-bleed.yaml',
  ),
  'attack-cloud-imds' => 
  array (
    'id' => 'attack-cloud-imds',
    'kind' => 'attack',
    'title' => 'Cloud Imds',
    'category' => 'ssrf',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/90-imds.yaml',
  ),
  'attack-cmdi-unix' => 
  array (
    'id' => 'attack-cmdi-unix',
    'kind' => 'attack',
    'title' => 'Cmdi Unix',
    'category' => 'rce',
    'cve' => '',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/41-cmdi-unix.yaml',
  ),
  'attack-cmdi-windows' => 
  array (
    'id' => 'attack-cmdi-windows',
    'kind' => 'attack',
    'title' => 'Cmdi Windows',
    'category' => 'rce',
    'cve' => '',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/40-cmdi-windows.yaml',
  ),
  'attack-confluence-26134' => 
  array (
    'id' => 'attack-confluence-26134',
    'kind' => 'attack',
    'title' => 'Confluence 26134',
    'category' => 'rce',
    'cve' => 'CVE-2022-26134',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/05-confluence-ognl.yaml',
  ),
  'attack-f5-1388' => 
  array (
    'id' => 'attack-f5-1388',
    'kind' => 'attack',
    'title' => 'F5 1388',
    'category' => 'rce',
    'cve' => 'CVE-2022-1388',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/74-f5-icontrol.yaml',
  ),
  'attack-fortios-40684' => 
  array (
    'id' => 'attack-fortios-40684',
    'kind' => 'attack',
    'title' => 'Fortios 40684',
    'category' => 'other',
    'cve' => 'CVE-2022-40684',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/80-fortios.yaml',
  ),
  'attack-geoserver-36401' => 
  array (
    'id' => 'attack-geoserver-36401',
    'kind' => 'attack',
    'title' => 'Geoserver 36401',
    'category' => 'rce',
    'cve' => 'CVE-2024-36401',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/78-geoserver.yaml',
  ),
  'attack-ivanti-21887' => 
  array (
    'id' => 'attack-ivanti-21887',
    'kind' => 'attack',
    'title' => 'Ivanti 21887',
    'category' => 'rce',
    'cve' => 'CVE-2023-46805',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/82-ivanti.yaml',
  ),
  'attack-lfi-environ' => 
  array (
    'id' => 'attack-lfi-environ',
    'kind' => 'attack',
    'title' => 'Lfi Environ',
    'category' => 'lfi',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/25-lfi-environ.yaml',
  ),
  'attack-lfi-group' => 
  array (
    'id' => 'attack-lfi-group',
    'kind' => 'attack',
    'title' => 'Lfi Group',
    'category' => 'lfi',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/29-lfi-group.yaml',
  ),
  'attack-lfi-shadow' => 
  array (
    'id' => 'attack-lfi-shadow',
    'kind' => 'attack',
    'title' => 'Lfi Shadow',
    'category' => 'lfi',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/28-lfi-shadow.yaml',
  ),
  'attack-lfi-smbconf' => 
  array (
    'id' => 'attack-lfi-smbconf',
    'kind' => 'attack',
    'title' => 'Lfi Smbconf',
    'category' => 'lfi',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/24-lfi-smbconf.yaml',
  ),
  'attack-lfi-unix' => 
  array (
    'id' => 'attack-lfi-unix',
    'kind' => 'attack',
    'title' => 'Lfi Unix',
    'category' => 'lfi',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/31-lfi-unix.yaml',
  ),
  'attack-lfi-windows' => 
  array (
    'id' => 'attack-lfi-windows',
    'kind' => 'attack',
    'title' => 'Lfi Windows',
    'category' => 'lfi',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/30-lfi-windows.yaml',
  ),
  'attack-open-redirect' => 
  array (
    'id' => 'attack-open-redirect',
    'kind' => 'attack',
    'title' => 'Open Redirect',
    'category' => 'redirect',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/60-open-redirect.yaml',
  ),
  'attack-owncloud-49103' => 
  array (
    'id' => 'attack-owncloud-49103',
    'kind' => 'attack',
    'title' => 'Owncloud 49103',
    'category' => 'other',
    'cve' => 'CVE-2023-49103',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/74-owncloud-graphapi.yaml',
  ),
  'attack-php-glastopf' => 
  array (
    'id' => 'attack-php-glastopf',
    'kind' => 'attack',
    'title' => 'Php Glastopf',
    'category' => 'rce',
    'cve' => '',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/46-php-glastopf.yaml',
  ),
  'attack-phpcgi-1823' => 
  array (
    'id' => 'attack-phpcgi-1823',
    'kind' => 'attack',
    'title' => 'Phpcgi 1823',
    'category' => 'other',
    'cve' => 'CVE-2012-1823',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/08-phpcgi-source.yaml',
  ),
  'attack-phpcgi-4577' => 
  array (
    'id' => 'attack-phpcgi-4577',
    'kind' => 'attack',
    'title' => 'Phpcgi 4577',
    'category' => 'rce',
    'cve' => 'CVE-2024-4577',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/09-phpcgi-4577.yaml',
  ),
  'attack-phpunit-rce' => 
  array (
    'id' => 'attack-phpunit-rce',
    'kind' => 'attack',
    'title' => 'Phpunit Rce',
    'category' => 'rce',
    'cve' => 'CVE-2017-9841',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/15-phpunit-rce.yaml',
  ),
  'attack-shellshock' => 
  array (
    'id' => 'attack-shellshock',
    'kind' => 'attack',
    'title' => 'Shellshock',
    'category' => 'rce',
    'cve' => 'CVE-2014-6271',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/10-shellshock.yaml',
  ),
  'attack-spring-actuator' => 
  array (
    'id' => 'attack-spring-actuator',
    'kind' => 'attack',
    'title' => 'Spring Actuator',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/88-spring-actuator.yaml',
  ),
  'attack-sqli' => 
  array (
    'id' => 'attack-sqli',
    'kind' => 'attack',
    'title' => 'Sqli',
    'category' => 'sqli',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/50-sqli.yaml',
  ),
  'attack-ssti-numeric' => 
  array (
    'id' => 'attack-ssti-numeric',
    'kind' => 'attack',
    'title' => 'Ssti Numeric',
    'category' => 'ssti',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/45-ssti-numeric.yaml',
  ),
  'attack-ssti-twig' => 
  array (
    'id' => 'attack-ssti-twig',
    'kind' => 'attack',
    'title' => 'Ssti Twig',
    'category' => 'ssti',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/44-ssti-twig.yaml',
  ),
  'attack-struts-ognl' => 
  array (
    'id' => 'attack-struts-ognl',
    'kind' => 'attack',
    'title' => 'Struts Ognl',
    'category' => 'rce',
    'cve' => 'CVE-2017-5638',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/12-struts-ognl.yaml',
  ),
  'attack-thinkphp-rce' => 
  array (
    'id' => 'attack-thinkphp-rce',
    'kind' => 'attack',
    'title' => 'Thinkphp Rce',
    'category' => 'rce',
    'cve' => '',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/72-thinkphp.yaml',
  ),
  'attack-webshell-panel' => 
  array (
    'id' => 'attack-webshell-panel',
    'kind' => 'attack',
    'title' => 'Webshell Panel',
    'category' => 'other',
    'cve' => '',
    'severity' => 'critical',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/86-webshell.yaml',
  ),
  'attack-xss' => 
  array (
    'id' => 'attack-xss',
    'kind' => 'attack',
    'title' => 'Xss',
    'category' => 'xss',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/65-xss-reflect.yaml',
  ),
  'attack-xxe' => 
  array (
    'id' => 'attack-xxe',
    'kind' => 'attack',
    'title' => 'Xxe',
    'category' => 'xxe',
    'cve' => '',
    'severity' => 'high',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/attack/20-xxe.yaml',
  ),
  'nuclei-reflection' => 
  array (
    'id' => 'nuclei-reflection',
    'kind' => 'corpus',
    'title' => 'Nuclei detection reflection',
    'category' => 'reflection',
    'cve' => '',
    'severity' => 'varies',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'resources/compiled/nuclei-index.full.php',
    'count' => 6343,
  ),
  'route-adminer' => 
  array (
    'id' => 'route-adminer',
    'kind' => 'route',
    'title' => 'Adminer',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/140-adminer.yaml',
  ),
  'route-apache-server-status' => 
  array (
    'id' => 'route-apache-server-status',
    'kind' => 'route',
    'title' => 'Apache Server Status',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/80-apache-server-status.yaml',
  ),
  'route-basic-auth' => 
  array (
    'id' => 'route-basic-auth',
    'kind' => 'route',
    'title' => 'Basic Auth',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/220-basic-auth.yaml',
  ),
  'route-citrix' => 
  array (
    'id' => 'route-citrix',
    'kind' => 'route',
    'title' => 'Citrix',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/170-citrix.yaml',
  ),
  'route-credentials-txt' => 
  array (
    'id' => 'route-credentials-txt',
    'kind' => 'route',
    'title' => 'Credentials Txt',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/230-credentials-txt.yaml',
  ),
  'route-directory-listing' => 
  array (
    'id' => 'route-directory-listing',
    'kind' => 'route',
    'title' => 'Directory Listing',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/180-directory-listing.yaml',
  ),
  'route-django-admin' => 
  array (
    'id' => 'route-django-admin',
    'kind' => 'route',
    'title' => 'Django Admin',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/190-django-admin.yaml',
  ),
  'route-dotenv' => 
  array (
    'id' => 'route-dotenv',
    'kind' => 'route',
    'title' => 'Dotenv',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/20-dotenv.yaml',
  ),
  'route-exchange-owa' => 
  array (
    'id' => 'route-exchange-owa',
    'kind' => 'route',
    'title' => 'Exchange Owa',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/130-exchange-owa.yaml',
  ),
  'route-git-config' => 
  array (
    'id' => 'route-git-config',
    'kind' => 'route',
    'title' => 'Git Config',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/10-git-config.yaml',
  ),
  'route-htpasswd' => 
  array (
    'id' => 'route-htpasswd',
    'kind' => 'route',
    'title' => 'Htpasswd',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/70-htpasswd.yaml',
  ),
  'route-joomla' => 
  array (
    'id' => 'route-joomla',
    'kind' => 'route',
    'title' => 'Joomla',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/150-joomla.yaml',
  ),
  'route-package-json' => 
  array (
    'id' => 'route-package-json',
    'kind' => 'route',
    'title' => 'Package Json',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/90-package-json.yaml',
  ),
  'route-phpinfo' => 
  array (
    'id' => 'route-phpinfo',
    'kind' => 'route',
    'title' => 'Phpinfo',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/60-phpinfo.yaml',
  ),
  'route-phpmyadmin' => 
  array (
    'id' => 'route-phpmyadmin',
    'kind' => 'route',
    'title' => 'Phpmyadmin',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/240-phpmyadmin.yaml',
  ),
  'route-sql-backup' => 
  array (
    'id' => 'route-sql-backup',
    'kind' => 'route',
    'title' => 'Sql Backup',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/233-sql-backup.yaml',
  ),
  'route-sql-dump' => 
  array (
    'id' => 'route-sql-dump',
    'kind' => 'route',
    'title' => 'Sql Dump',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/110-sql-dump.yaml',
  ),
  'route-ssh-private-key' => 
  array (
    'id' => 'route-ssh-private-key',
    'kind' => 'route',
    'title' => 'Ssh Private Key',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/100-ssh-private-key.yaml',
  ),
  'route-terraform-tfstate' => 
  array (
    'id' => 'route-terraform-tfstate',
    'kind' => 'route',
    'title' => 'Terraform Tfstate',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/231-terraform-tfstate.yaml',
  ),
  'route-tomcat-manager' => 
  array (
    'id' => 'route-tomcat-manager',
    'kind' => 'route',
    'title' => 'Tomcat Manager',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/200-tomcat-manager.yaml',
  ),
  'route-users-csv' => 
  array (
    'id' => 'route-users-csv',
    'kind' => 'route',
    'title' => 'Users Csv',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/232-users-csv.yaml',
  ),
  'route-weblogic' => 
  array (
    'id' => 'route-weblogic',
    'kind' => 'route',
    'title' => 'Weblogic',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/120-weblogic.yaml',
  ),
  'route-wp-config' => 
  array (
    'id' => 'route-wp-config',
    'kind' => 'route',
    'title' => 'Wp Config',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/40-wp-config.yaml',
  ),
  'route-wp-login' => 
  array (
    'id' => 'route-wp-login',
    'kind' => 'route',
    'title' => 'Wp Login',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/50-wp-login.yaml',
  ),
  'route-wp-readme' => 
  array (
    'id' => 'route-wp-readme',
    'kind' => 'route',
    'title' => 'Wp Readme',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/160-wp-readme.yaml',
  ),
  'route-xmlrpc' => 
  array (
    'id' => 'route-xmlrpc',
    'kind' => 'route',
    'title' => 'Xmlrpc',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'info',
    'default' => true,
    'ports' => 
    array (
    ),
    'source' => 'templates/route/30-xmlrpc.yaml',
  ),
  'service-clamav' => 
  array (
    'id' => 'service-clamav',
    'kind' => 'service',
    'title' => 'ClamAV clamd',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 3310,
    ),
    'source' => 'templates/protocol/clamav.yaml',
  ),
  'service-ethernet-ip' => 
  array (
    'id' => 'service-ethernet-ip',
    'kind' => 'service',
    'title' => 'EtherNet/IP CIP (Allen-Bradley CompactLogix)',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 44818,
    ),
    'source' => 'templates/protocol/ethernet-ip.yaml',
  ),
  'service-finger' => 
  array (
    'id' => 'service-finger',
    'kind' => 'service',
    'title' => 'Finger User Info Service',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 79,
    ),
    'source' => 'templates/protocol/finger.yaml',
  ),
  'service-ftp' => 
  array (
    'id' => 'service-ftp',
    'kind' => 'service',
    'title' => 'FTP',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 21,
    ),
    'source' => 'templates/protocol/ftp.yaml',
  ),
  'service-imap' => 
  array (
    'id' => 'service-imap',
    'kind' => 'service',
    'title' => 'IMAP Mail Server',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 143,
    ),
    'source' => 'templates/protocol/imap.yaml',
  ),
  'service-memcached' => 
  array (
    'id' => 'service-memcached',
    'kind' => 'service',
    'title' => 'MEMCACHED',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 11211,
    ),
    'source' => 'templates/protocol/memcached.yaml',
  ),
  'service-modbus' => 
  array (
    'id' => 'service-modbus',
    'kind' => 'service',
    'title' => 'Modbus TCP (Schneider Modicon M340)',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 502,
    ),
    'source' => 'templates/protocol/modbus.yaml',
  ),
  'service-mongodb' => 
  array (
    'id' => 'service-mongodb',
    'kind' => 'service',
    'title' => 'MongoDB Server',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 27017,
    ),
    'source' => 'templates/protocol/mongodb.yaml',
  ),
  'service-mysql' => 
  array (
    'id' => 'service-mysql',
    'kind' => 'service',
    'title' => 'MySQL Server',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 3306,
    ),
    'source' => 'templates/protocol/mysql.yaml',
  ),
  'service-pop3' => 
  array (
    'id' => 'service-pop3',
    'kind' => 'service',
    'title' => 'POP3 Mail Server',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 110,
    ),
    'source' => 'templates/protocol/pop3.yaml',
  ),
  'service-postgresql' => 
  array (
    'id' => 'service-postgresql',
    'kind' => 'service',
    'title' => 'PostgreSQL Server',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 5432,
    ),
    'source' => 'templates/protocol/postgresql.yaml',
  ),
  'service-redis' => 
  array (
    'id' => 'service-redis',
    'kind' => 'service',
    'title' => 'REDIS',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 6379,
    ),
    'source' => 'templates/protocol/redis.yaml',
  ),
  'service-rsync' => 
  array (
    'id' => 'service-rsync',
    'kind' => 'service',
    'title' => 'Rsync Daemon',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 873,
    ),
    'source' => 'templates/protocol/rsync.yaml',
  ),
  'service-smtp' => 
  array (
    'id' => 'service-smtp',
    'kind' => 'service',
    'title' => 'SMTP',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 25,
    ),
    'source' => 'templates/protocol/smtp.yaml',
  ),
  'service-ssh' => 
  array (
    'id' => 'service-ssh',
    'kind' => 'service',
    'title' => 'SSH',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 2222,
    ),
    'source' => 'templates/protocol/ssh.yaml',
  ),
  'service-telnet' => 
  array (
    'id' => 'service-telnet',
    'kind' => 'service',
    'title' => 'TELNET',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 23,
    ),
    'source' => 'templates/protocol/telnet.yaml',
  ),
  'service-vnc' => 
  array (
    'id' => 'service-vnc',
    'kind' => 'service',
    'title' => 'VNC (RFB) Remote Framebuffer',
    'category' => 'service',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 5900,
    ),
    'source' => 'templates/protocol/vnc.yaml',
  ),
  'service-zookeeper' => 
  array (
    'id' => 'service-zookeeper',
    'kind' => 'service',
    'title' => 'Apache ZooKeeper',
    'category' => 'exposure',
    'cve' => '',
    'severity' => 'medium',
    'default' => true,
    'ports' => 
    array (
      0 => 2181,
    ),
    'source' => 'templates/protocol/zookeeper.yaml',
  ),
);
